version: 1
disable_existing_loggers: False

formatters:
  # Formatter for application logs
  default:
    (): "uvicorn.logging.DefaultFormatter"
    fmt: "%(levelprefix)s %(asctime)s [%(name)s] :: %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  # Formatter for server access logs (GET/POST requests)
  access:
    (): "uvicorn.logging.AccessFormatter"
    fmt: '%(levelprefix)s %(client_addr)s - "%(request_line)s" %(status_code)s'

handlers:
  # Handler for application logs, prints to console
  default:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stderr
  # Handler for access logs, prints to console
  access:
    formatter: access
    class: logging.StreamHandler
    stream: ext://sys.stdout

loggers:
  # Logger for your main application
  __main__:
    handlers: [default]
    level: INFO
    propagate: no
  # Loggers for your extractor modules
  extractor:
    handlers: [default]
    level: INFO
  table_extractor:
    handlers: [default]
    level: INFO
  text_extractor:
    handlers: [default]
    level: INFO
  
  # Uvicorn's own loggers
  uvicorn.error:
    level: INFO
  uvicorn.access:
    handlers: [access]
    level: INFO
    propagate: no

root:
  handlers: [default]
  level: WARNING